import 'package:movie_app/data/vos/actor_vo.dart';
import 'package:movie_app/data/vos/genre_vo.dart';
import 'package:movie_app/data/vos/movie_vo.dart';

List<MovieVO> getMockMovieForTest() {
  return [
    MovieVO(
        false,
        "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
        [16, 10751, 35, 14],
        508947,
        "en",
        "Turning Red",
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
        5126.644,
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        "2022-03-01",
        "Turning Red",
        false,
        7.5,
        1450,
        null,
        200000000,
        null,
        "https://www.warnerbros.com/movies/wonder-woman-1984",
        null,
        null,
        null,
        165160005,
        151,
        null,
        "Released",
        "A new era of wonder begins.",
        true,
        false,
        false),
    MovieVO(
        false,
        "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
        [16, 10751, 35, 14],
        508947,
        "en",
        "Turning Red",
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
        5126.644,
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        "2022-03-01",
        "Turning Red",
        false,
        7.5,
        1450,
        null,
        200000000,
        null,
        "https://www.warnerbros.com/movies/wonder-woman-1984",
        null,
        null,
        null,
        165160005,
        151,
        null,
        "Released",
        "A new era of wonder begins.",
        false,
        true,
        false),
    MovieVO(
        false,
        "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
        [16, 10751, 35, 14],
        508947,
        "en",
        "Turning Red",
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
        5126.644,
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        "2022-03-01",
        "Turning Red",
        false,
        7.5,
        1450,
        null,
        200000000,
        null,
        "https://www.warnerbros.com/movies/wonder-woman-1984",
        null,
        null,
        null,
        165160005,
        151,
        null,
        "Released",
        "A new era of wonder begins.",
        false,
        false,
        true),
  ];
}

List<ActorVO> getMockActorForTest() {
  return [
    ActorVO(
      false,
      1,
      1726321,
      null,
      "Acting",
      "Camilla Roholm",
      3.333,
      "/feaxjgK6F8egTGwlmrZHvN9TftR.jpg",
      null,
      120,
      "Amazon",
      "5fe68fe34539d0003da04799",
      23,
    ),
    ActorVO(
      false,
      1,
      996220,
      null,
      "Crew",
      "Jessie Graff",
      2.319,
      "/ePoVxfGq9LUj8RJ9FfmViNFqcBB.jpg",
      null,
      121,
      "Competitor",
      "5fe68ff6e18b97003d8c6a3f",
      24,
    ),
    ActorVO(
      false,
      1,
      2205383,
      null,
      "Acting",
      "Bronte Lavine",
      0.6,
      "/eUgAOw9MsylIH9Ryf6pqBDUE2fb.jpg",
      null,
      122,
      "Competitor",
      "5fe690014539d0003da047c6",
      25,
    ),
  ];
}

List<GenreVO> getMockGenreForTest() {
  return [
    GenreVO(1, "Action"),
    GenreVO(2, "Adventure"),
    GenreVO(3, "Animation"),
  ];
}
