import 'package:movie_app/data/vos/actor_vo.dart';
import 'package:movie_app/data/vos/genre_vo.dart';
import 'package:movie_app/data/vos/movie_vo.dart';

List<MovieVO> getMockMovieForTest() {
  return [
    MovieVO(
        false,
        "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
        [16, 10751, 35, 14],
        508947,
        "en",
        "Turning Red",
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
        5126.644,
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        "2022-03-01",
        "Turning Red",
        false,
        7.5,
        1450,
        null,
        200000000,
        null,
        "https://www.warnerbros.com/movies/wonder-woman-1984",
        null,
        null,
        null,
        165160005,
        151,
        null,
        "Released",
        "A new era of wonder begins.",
        true,
        false,
        false),
    MovieVO(
        false,
        "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
        [16, 10751, 35, 14],
        508947,
        "en",
        "Turning Red",
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
        5126.644,
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        "2022-03-01",
        "Turning Red",
        false,
        7.5,
        1450,
        null,
        200000000,
        null,
        "https://www.warnerbros.com/movies/wonder-woman-1984",
        null,
        null,
        null,
        165160005,
        151,
        null,
        "Released",
        "A new era of wonder begins.",
        false,
        true,
        false),
    MovieVO(
        false,
        "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
        [16, 10751, 35, 14],
        508947,
        "en",
        "Turning Red",
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
        5126.644,
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        "2022-03-01",
        "Turning Red",
        false,
        7.5,
        1450,
        null,
        200000000,
        null,
        "https://www.warnerbros.com/movies/wonder-woman-1984",
        null,
        null,
        null,
        165160005,
        151,
        null,
        "Released",
        "A new era of wonder begins.",
        false,
        false,
        true),
  ];
}

List<ActorVO> getMockActorForTest() {
  return [
    ActorVO(
        false,
        1,
        90633,
        null,
        "Acting",
        "Gal Gadot",
        56.593,
        "/plLfB60M5cJrnog8KvAKhI4UJuk.jpg",
        "Gal Gadot",
        0,
        "Diana Prince / Wonder Woman",
        "595686e4c3a368382e050da4",
        0),
    ActorVO(
        false,
        2,
        62064,
        null,
        "Acting",
        "Chris Pine",
        32.022,
        "/ipG3BMO8Ckv9xVeEY27lzq975Qm.jpg",
        "Chris Pine",
        15,
        "Steve Trevor",
        "5b0b4526c3a3684adc0097a5",
        1),
    ActorVO(
        false,
        1,
        41091,
        null,
        "Acting",
        "Kristen Wiig",
        19.27,
        "/N517EQh7j4mNl3BStMmjMN6hId.jpg",
        "Kristen Wiig",
        12,
        "Barbara Minerva / Cheetah",
        "5a975236c3a36861510077f1",
        2),
  ];
}

List<GenreVO> getMockGenreForTest() {
  return [
    GenreVO(28, "Action"),
    GenreVO(12, "Adventure"),
    GenreVO(16, "Animation"),
  ];
}
